apiVersion: v1
kind: Pod
metadata:
   name: notification-pod
spec:
   containers:
   - name: notification-container01
     image: seyfullah.cank/notification:latest
     ports:
     - containerPort: 6379